import os
import torch

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
CHECKPOINT_DIR = os.path.join(BASE_DIR, "checkpoints")
LOG_DIR = os.path.join(BASE_DIR, "logs")
os.makedirs(CHECKPOINT_DIR, exist_ok=True)
os.makedirs(LOG_DIR, exist_ok=True)

CHECKPOINT_VERSION = "route_b_v2"
CHECKPOINT_SUFFIX = "_b"

# 棋盘与特征
BOARD_SIZE = 100
CHANNELS = 17

# 网络
RES_BLOCKS = 6
RES_FILTERS = 64
MAX_MACRO_SLOTS = 32  # 与 CANDIDATE_CAP 一致

# candidates_b
CANDIDATE_CAP = 32
BEAM_WIDTH = 8
MAX_SOURCES = 6
MAX_TARGETS_PER_SRC = 4
MAX_SOURCES_PROBE = 6
SWARM_ETA_GAP = 2
MAX_DUAL_SWARMS = 6
MAX_TRIPLE_SWARMS = 3
REINFORCE_MAX = 4
REINFORCE_ETA_HORIZON = 12
REINFORCE_DEFICIT_SCALE = 1.15
MAX_COMBO_MACROS = 5
MAX_TWO_TARGET_MACROS = 5
MATCH_QUALITY_THRESHOLD = 0.85
MATCH_ANGLE_TOL_DEG = 8.0
TWO_TARGET_ETA_GAP = 3
BEAM_CUTOFF_RATIO = 0.25
SWARM_MIN_TARGET_PROD = 2

# MCTS
MCTS_SIMULATIONS = 128
SUBMIT_MCTS_SIMULATIONS = 128
C_PUCT = 1.5
DIRICHLET_ALPHA = 0.3
DIRICHLET_EPSILON = 0.15
OPPONENT_ROLLOUT_DEEPSEEK_PROB = 0.5
CONF_THRESHOLD = 0.12
HYBRID_V1_ON_LOW_CONF = True

# 训练对局
NUM_PARALLEL_GAMES = 8
MAX_GAME_STEPS = 500
ENV_RUN_TIMEOUT = 7200  # 单局最长秒数（Kaggle 默认 1200，deepseek 自博弈易超时）
TRAIN_TWO_PLAYER_PROB = 0.4
PRETRAIN_NUM_AGENTS = 2  # IL 固定 2P，比 4P deepseek 自博弈快很多
MAX_FLEETS_PER_TURN = 3
GAME_EVAL_EPISODES = 30
EVAL_MCTS_SIMULATIONS = 64

# 训练超参
BATCH_SIZE = 128
LEARNING_RATE = 1e-3
WEIGHT_DECAY = 1e-4
REPLAY_BUFFER_SIZE = 10000
TRAIN_EPOCHS_PER_ITER = 5
POLICY_LOSS_WEIGHT = 1.0
VALUE_LOSS_WEIGHT = 1.0
VALUE_TARGET_SCALE = 100.0
SAVE_EVERY_ITERS = 20
EVAL_EVERY_ITERS = 50
MAX_ITERATIONS = 100000
TRAIN_MCTS_SIMULATIONS = 24
MCTS_SIM_FULL = 48
MCTS_SIM_BOOST_ITER = 50
TEMPERATURE_STEPS = 20
PRETRAIN_GAMES = 280
PRETRAIN_TRAIN_STEPS = 800
PRETRAIN_RESERVOIR_CHECKPOINT = "pretrain_reservoir"
PRETRAIN_RESERVOIR_SAVE_EVERY = 10
FORCE_REPRETRAIN = False
DEEPSEEK_START_ITER = 300
POOL_START_ITER = 400
DEEPSEEK_OPP_PROB = 0.25

INTERRUPT_CHECKPOINT = "interrupt"
LATEST_CHECKPOINT = "latest"
PRETRAINED_CHECKPOINT = "pretrained"
PRETRAIN_PROGRESS_CHECKPOINT = "pretrain_progress"
REPLAY_CHECKPOINT = "replay"


def orbit_wars_config(**overrides):
    """本地训练用 env 配置（提高 runTimeout，避免 DeadlineExceeded）。"""
    cfg = {"episodeSteps": MAX_GAME_STEPS, "runTimeout": ENV_RUN_TIMEOUT}
    cfg.update(overrides)
    return cfg

V3_BACKBONE_PATH = os.path.normpath(
    os.path.join(BASE_DIR, "..", "v3_NN", "checkpoints", "latest.pt")
)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
NUM_WORKERS = 8
